using System.Text;
using Fusion.Legacy.Analyzer.Model;

namespace Fusion.Legacy.Analyzer.PostgreSql;

public static class PostgresSqlGenerator
{
    public static string GenerateSchema(DatabaseModel database)
    {
        ArgumentNullException.ThrowIfNull(database);

        var sql = new StringBuilder();

        sql.AppendLine("-- Gerado por Fusion.Legacy.Analyzer");
        sql.AppendLine("-- Estrutura extraída do Microsoft Access");
        sql.AppendLine("BEGIN;");
        sql.AppendLine();

        foreach (var table in database.Tables.OrderBy(item => item.Name))
        {
            AppendCreateTable(sql, table);
            sql.AppendLine();
        }

        foreach (var table in database.Tables.OrderBy(item => item.Name))
        {
            AppendIndexes(sql, table);
        }

        foreach (var table in database.Tables.OrderBy(item => item.Name))
        {
            AppendForeignKeys(sql, table);
        }

        sql.AppendLine("COMMIT;");
        return sql.ToString();
    }

    public static void WriteSchemaFile(DatabaseModel database, string outputPath)
    {
        if (string.IsNullOrWhiteSpace(outputPath))
            throw new ArgumentException("O caminho de saída não foi informado.", nameof(outputPath));

        var fullPath = Path.GetFullPath(outputPath);
        var directory = Path.GetDirectoryName(fullPath);

        if (!string.IsNullOrEmpty(directory))
            Directory.CreateDirectory(directory);

        File.WriteAllText(fullPath, GenerateSchema(database), new UTF8Encoding(false));
    }

    private static void AppendCreateTable(StringBuilder sql, TableModel table)
    {
        sql.Append("CREATE TABLE ")
            .Append(PostgresIdentifier.Quote(table.Name))
            .AppendLine(" (");

        var definitions = new List<string>();

        foreach (var column in table.Columns.OrderBy(item => item.OrdinalPosition))
        {
            var definition = new StringBuilder();
            definition.Append("    ")
                .Append(PostgresIdentifier.Quote(column.Name))
                .Append(' ')
                .Append(PostgresTypeMapper.Map(column));

            if (column.IsAutoIncrement)
                definition.Append(" GENERATED BY DEFAULT AS IDENTITY");

            if (!column.IsNullable)
                definition.Append(" NOT NULL");

            definitions.Add(definition.ToString());
        }

        var primaryKey = table.Indexes.FirstOrDefault(index => index.IsPrimaryKey);

        if (primaryKey is not null && primaryKey.Columns.Count > 0)
        {
            var columns = string.Join(", ", primaryKey.Columns
                .OrderBy(item => item.OrdinalPosition)
                .Select(item => PostgresIdentifier.Quote(item.Name)));

            definitions.Add(
                $"    CONSTRAINT {PostgresIdentifier.Quote(BuildObjectName(table.Name, primaryKey.Name))} " +
                $"PRIMARY KEY ({columns})");
        }

        sql.AppendLine(string.Join("," + Environment.NewLine, definitions));
        sql.AppendLine(");");
    }

    private static void AppendIndexes(StringBuilder sql, TableModel table)
    {
        foreach (var index in table.Indexes
                     .Where(item => !item.IsPrimaryKey)
                     .OrderBy(item => item.Name))
        {
            if (index.Columns.Count == 0)
                continue;

            var columns = string.Join(", ", index.Columns
                .OrderBy(item => item.OrdinalPosition)
                .Select(item => PostgresIdentifier.Quote(item.Name)));

            sql.Append("CREATE ");

            if (index.IsUnique)
                sql.Append("UNIQUE ");

            sql.Append("INDEX ")
                .Append(PostgresIdentifier.Quote(BuildObjectName(table.Name, index.Name)))
                .Append(" ON ")
                .Append(PostgresIdentifier.Quote(table.Name))
                .Append(" (")
                .Append(columns)
                .AppendLine(");");
        }

        if (table.Indexes.Any(item => !item.IsPrimaryKey))
            sql.AppendLine();
    }

    private static void AppendForeignKeys(StringBuilder sql, TableModel table)
    {
        foreach (var foreignKey in table.ForeignKeys.OrderBy(item => item.Name))
        {
            if (foreignKey.Columns.Count == 0)
                continue;

            var sourceColumns = string.Join(", ", foreignKey.Columns
                .OrderBy(item => item.OrdinalPosition)
                .Select(item => PostgresIdentifier.Quote(item.ColumnName)));

            var targetColumns = string.Join(", ", foreignKey.Columns
                .OrderBy(item => item.OrdinalPosition)
                .Select(item => PostgresIdentifier.Quote(item.ReferencedColumnName)));

            sql.Append("ALTER TABLE ")
                .Append(PostgresIdentifier.Quote(table.Name))
                .Append(" ADD CONSTRAINT ")
                .Append(PostgresIdentifier.Quote(BuildObjectName(table.Name, foreignKey.Name)))
                .Append(" FOREIGN KEY (")
                .Append(sourceColumns)
                .Append(") REFERENCES ")
                .Append(PostgresIdentifier.Quote(foreignKey.ReferencedTable))
                .Append(" (")
                .Append(targetColumns)
                .Append(')');

            if (foreignKey.CascadeUpdate)
                sql.Append(" ON UPDATE CASCADE");

            if (foreignKey.CascadeDelete)
                sql.Append(" ON DELETE CASCADE");

            sql.AppendLine(";");
        }

        if (table.ForeignKeys.Count > 0)
            sql.AppendLine();
    }

    private static string BuildObjectName(string tableName, string objectName)
    {
        var name = $"{tableName}__{objectName}";
        const int postgresIdentifierLimit = 63;

        if (name.Length <= postgresIdentifierLimit)
            return name;

        var hash = Convert.ToHexString(
            System.Security.Cryptography.SHA256.HashData(
                Encoding.UTF8.GetBytes(name)))[..8].ToLowerInvariant();

        var prefixLength = postgresIdentifierLimit - hash.Length - 1;
        return $"{name[..prefixLength]}_{hash}";
    }
}
